import ReactQueryProvider from "@/components/providers/react-query-provider";
import "antd/dist/reset.css";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/components/layout/navbar";
export const metadata: Metadata = {
  title: "فروشگاه ProStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <ReactQueryProvider>
          <Navbar />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
